steps:
- name: requirements
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
- name: build
  entrypoint: python
  args: ["-m", "build"]
- name: push
  entrypoint: python
  args:
  - '-m'
  - 'twine'
  - 'upload'
  - '--repository-url'
  - 'https://${_LOCATION}-python.pkg.dev/$PROJECT_ID/${_REPOSITORY}/'
  - 'dist/*'